### ISSUE TITLE
Vagrant file and development.rb disagree on hostname

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#186]
In the vagrantfile it defines the hostname and ip configuration as https://github.com/zwagoth/e621ng/blob/6eab79aa33f981a3e6391973c486487a5ac5ec8a/Vagrantfile#L19-L22

This contrasts what is presented in the `/config/environments/development.rb` file https://github.com/zwagoth/e621ng/blob/6eab79aa33f981a3e6391973c486487a5ac5ec8a/config/environments/development.rb#L62

With these being different, connecting to `e621.lc` in the browser will result in an error saying that e621.lc is a blocked host.

Correcting one of these should solve the issue. In my local setup, changing the development.rb to be `e621.lc` solved the issue.

**Comment by Sasquire** [comment]
As soon as I can figure out how to make a pull request proper.

https://github.com/Sasquire/e621ng/blob/a1e674916e9b896fec655d039fa856f857693141/config/environments/development.rb#L62

**Comment by Earlopain** [comment]
Fixed with https://github.com/zwagoth/e621ng/commit/f24c14307c4e86a514d565560e169e057bbb9fde
