### ISSUE TITLE
Seeder script fails due to no password confirmation

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#188]
Running the seeder script with `bundle exec rails db:seed` fails to properly seed the database with new information because the code to create new users lacks a password confirmation field.

https://github.com/zwagoth/e621ng/blob/6eab79aa33f981a3e6391973c486487a5ac5ec8a/db/seeds.rb#L18-L33

Simply adding a `password_confirmation` with the same password will fix the script and cause the database to be loaded with fake information.

**Comment by Earlopain** [comment]
See linked pull request.
