### ISSUE TITLE
Web Movies not working on Mobile

### ISSUE THREAD

**Issue by AHideouscube** [e621ng/e621ng#192]
I use google chrome on my IPad, but the same issue happens with Firefox and on my phone.

**Comment by Sasquire** [comment]
WEMB's are working for me, firefox 68.5.0 LineageOS. Can you give any more information such as version numbers and if your phone is an apple phone?

Edit: Perhaps this forum post is of use https://e621.net/forum_topics/25761

**Comment by Earlopain** [comment]
Should be fixed with the introduction of video rescales (webm to mp4)
