### ISSUE TITLE
User search autocompletion fails due to an unpermitted parameter

### ISSUE THREAD

**Issue by SafoSnep** [e621ng/e621ng#194]
Using the user search box on the website tries to autocomplete possible values with Javascript, but the request always fails with an error: `{"success": false,"reason": "found unpermitted parameter: :current_user_first"}`

I would have submitted a pull request to add the param here:
https://github.com/zwagoth/e621ng/blob/1dbd33e7d691c7f38174b872f129ea25782bdc0e/app/controllers/users_controller.rb#L131

but there's a related TODO which I'm not comfortable to touch:
https://github.com/zwagoth/e621ng/blob/e940c438acada76162264d0609f3a96cf05f36d7/app/models/user.rb#L842-L845

The autocompletion could be disabled in the Javascript code until the backend is fixed.

**Comment by kiranoot** [comment]
Fixed, but forgot to close the issue. Thank you for reporting it.
