### ISSUE TITLE
Unexpected behaviors in favorites.json

### ISSUE THREAD

**Issue by SafoSnep** [e621ng/e621ng#196]
1. Fetching favorites.json as a guest (without any authentication) returns HTML instead of JSON
2. Fetching favorites.json as a new user without any favorites fails with a generic error:
```json
{
  "success": false,
  "message": "An unexpected error occurred.",
  "code": "873c5a07-854c-46ee-979b-ef7a689917ce"
}
```

**Comment by Earlopain** [comment]
Adding to the second point: This generaly fails if you make a request which would not return favorites anymore. If I have 55 favorites and try to go to page 6 with a limit of 10 per page I will be getting 5 favorites. Going past page 6 will result in the afformentioned error.

Edit:
After typing this I remebered that setting a limit parameter on this endpoint has no effect. If you are logged in it will take the limit from your settings and if you are logged out it will be set to 75 no matter what you do.

**Comment by Earlopain** [comment]
I can't find the specific commit which fixed this but I don't run into this problem anymore.

**Comment by SafoSnep** [comment]
Confirmed as fixed.
