### ISSUE TITLE
posts.json randomly returns null value for url fields

### ISSUE THREAD

**Issue by DarkAlexZ** [e621ng/e621ng#198]
The title is self-explanatory. I haven't found any kind of pattern for this but this has been happening consistently since the site switched to this engine. I am calling posts.json without any parameters

Example:

> {"id":2174059,"created_at":"2020-03-08T18:30:34.057-04:00","updated_at":"2020-03-08T18:31:24.655-04:00","file":{"width":1000,"height":1417,"ext":"png","size":567492,"md5":"556fc1bba8551476084f34e43cac3774",**"url":null**},"preview":{"width":105,"height":150,**"url":null**},"sample":{"has":true,"height":1204,"width":850,**"url":null**},"score":{"up":0,"down":0,"total":0},"tags":{"general":["anatomically_correct","animal_genitalia","animal_penis","anthro","camping","cub","erection","genitals","hi_res","humanoid_genitalia","humanoid_penis","male","male/male","penis","young"],"species":["canid","canine","canis","domestic_dog","husky","mammal","nordic_sled_dog","spitz"],"character":[],"copyright":[],"artist":["bloodhawk","xanthe_(artist)","xanthewolf"],"invalid":[],"lore":[],"meta":[]},"locked_tags":[],"change_seq":26028544,"flags":{"pending":true,"flagged":false,"note_locked":false,"status_locked":false,"rating_locked":false,"deleted":false},"rating":"e","fav_count":0,"sources":["https://inkbunny.net/s/2104018"],"pools":[19210,19210],"relationships":{"parent_id":null,"has_children":false,"has_active_children":false,"children":[]},"approver_id":null,"uploader_id":163003,"description":"Page 8 of Max's Campout\n\nPage 20 is now up at https://subscribestar.adult/xanthe\n\nIt will be up on Bloodhawk's page soon, where you can already see the 1st previews of Camp Sunshine 3 😀","comment_count":0,"is_favorited":false}

**Comment by kiranoot** [comment]
This is an unfortunate side effect of the forced login for `young -rating:s` that was applied essentially for legal reasons. The same happens for deleted posts. I picked to fill entities with nulls instead of remove the fields because it allowed for better use in a strongly typed languages where fields shouldn't be optional in returns.

**Comment by Sasquire** [comment]
If we send an authenticated request to retrieve posts, will this filter be lifted and posts returned as expected?

Edit: Why am I asking. I can check myself.
It appears that when logged into the site it will return posts appropriately. I am unable to test with a request that doesn't have cookies but is authenticated at the moment. I expect it to work.
