### ISSUE TITLE
posts.json returns null in "has" field of "sample" for swf files

### ISSUE THREAD

**Issue by DarkAlexZ** [e621ng/e621ng#199]
Example:

> {"posts":[{"id":2052132,"created_at":"2019-11-12T14:25:30.778-05:00","updated_at":null,"file":{"width":1280,"height":1280,"ext":"swf","size":2244061,"md5":"4f2eb30415cb1c31ec7d5c7f304f070c","url":"https://static1.e621.net/data/4f/2e/4f2eb30415cb1c31ec7d5c7f304f070c.swf"},"preview":{"width":150,"height":150,"url":"https://static1.e621.net/images/download-preview.png"},"sample":{**"has":null**,"height":1280,"width":1280,"url":"https://static1.e621.net/data/4f/2e/4f2eb30415cb1c31ec7d5c7f304f070c.swf"},"score":{"up":0,"down":0,"total":24},"tags":{"general":["1:1","3d_animation","3d_(artwork)","animated","anthro","breasts","camel_toe","caught","clothed","clothing","dancing","daughter","digital_media_(artwork)","dress","female","flash","group","hi_res","mother","music","panties","parent","son","sound","suit","topless","underwear"],"species":["caracal","caracal_(genus)","felid","feline","mammal"],"character":["amanda_caracal","eric_caracal","ninfu_caracal"],"copyright":[],"artist":["angrycat_(artist)","littlefisky","sound_warning"],"invalid":[],"lore":[],"meta":[]},"locked_tags":[],"change_seq":23986142,"flags":{"pending":false,"flagged":false,"note_locked":false,"status_locked":false,"rating_locked":false,"deleted":false},"rating":"e","fav_count":57,"sources":["https://inkbunny.net/s/1302044"],"pools":[],"relationships":{"parent_id":null,"has_children":false,"has_active_children":false,"children":[]},"approver_id":38571,"uploader_id":134252,"description":"","comment_count":3,"is_favorited":false}]}

**Comment by kiranoot** [comment]
I have put in a fix for this and it should be deployed soon.
