### ISSUE TITLE
Multiple `id:<` search terms prefer the furthest right term

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#202]
If I were to make a search (for some unknown reason) of `cat id:<200 id:<100` the search would function as expected, returning all posts tagged with cat and having an id of less than 100. Conversely, searching `cat id:<100 id:<200` will return all posts tagged with cat and having an id less than 200.

**Comment by kiranoot** [comment]
This maintains the previous site behavior that metatags, unless explicitly set to do otherwise, may only have one value, and the last item in the list wins by overwriting the previous entry.

So this is "intended"

**Comment by Sasquire** [comment]
I would prefer removing the old site's feature and instead implement the search to work as expected. Especially because you can now search with `fav:` and receive the intersection of those two metatags. 

Edit: This would mean having searches like `width:1280 width:1281` return no posts. I think that is how it should operate as there are no posts with multiple widths. It would also allow searching for posts with a width or id in a specific range. e.g. `width:<1280 width:>640`.

**Comment by Deer-Spangle** [comment]
However, the overriding metatags functionality of the old site is very helpful for `order`. I know in the past, my projects have relied on the last order value taking precedence. With a base query of `order:random {user_query}` being able to be ordered by score if `user_query` is `cat order:score`.

I've also used it in the past to have a `score:>0` which can be overridden by a user wanting things with a low score, simply by adding a `score:<0` on their search.

Alternatively, given the recent changes already totally destroyed the API's backward compatibility, maybe it doesn't matter much? But worth it seemed worth adding the other side of this

**Comment by Sasquire** [comment]
You do have a point about the order. I am not sure how that would align with what I suggested earlier. There are situations where the reliance on position is useful, but I think that removing this in most situations will remove unexpected and unwanted behavior.

I don't know ruby, but I'll try and summarize the meta tags I find in [this file](https://github.com/zwagoth/e621ng/blob/f726c9f26403f4b106fe160b61db4f2b7b3ced38/app/logical/post_query_builder.rb) which I believe is the correct file.

Should follow set operations
* post_id
* post_id_negated
* mpixels
* ratio
* width
* score
* fav_count
* filesize
* change_seq
* date
* age
* post_tag_count
* pool
* uploader_id
* uploader_id_neg
* aprover_id
* approver_id_neg
* disapproval
* disapproval_neg
* flagger_ids
* flagger_ids_neg
* appealer_ids
* appealer_ids_neg
* commenter_ids
* noter_ids
* note_updater_ids
* artcomm_ids
* parent
* parent_neg_ids
* child
* pixiv_id
* upvote
* downvote

Having multiples should return no posts when appropriate but they don't accept ranges
* md5
* status
* status_neg
* filetype
* filetype_neg
* source
* source_neg
* rating
* locked
* locked_negated
* ordpool
* favgroups_neg
* favgroups

Rely on right/lest most term
* order

Again, I think that having results returned as expected is what we should strive to accomplish. The right reliance is an unintended "feature" that helps create neat workarounds, but does not help people using the site through their browser. It can create confusing situations such as when a user wants to search for a post posted between two and five days ago.

**Comment by Earlopain** [comment]
I have made improvements to search in #543, https://github.com/e621ng/e621ng/commit/9d2a4d6996f8fc9dd3028e3482cdde2bfe779127 and some other commits so that metatags are basically handled like normal tags are. `-` and `~` work, and specifying something twice returns no results.

There are a few exceptions:

- `order` and `randseed` because having multiple of those makes no sense
- `status` because there are places internally that expect only one status to exist
- `md5`
- `id`
- `child`
- All metatags that take true/false as a value, like `hassource`

I know this issue was originally about id searches but since you also listed all the other metatags I feel like I can close this. If you have usecases that requires one the exceptions to work feel free to make another issue.
