### ISSUE TITLE
posts.json returns HTML with 200 response when requesting a destroyed/unkown post

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#203]
Title is self explanatory. When trying to access the [three millionth post](https://e621.net/posts/3000000.json), it redirects the user to an HTML page and with a status code of 200. Expected result is a 404 response code along with text that json parsers will parse as null/undefined.

This behavior is consistent with destroyed posts, but I am weary about mentioning the id's of destroyed posts.

**Comment by kiranoot** [comment]
I have put in a fix for this and it should be deployed soon.
