### ISSUE TITLE
Deleted posts with children will only report having children sometimes

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#204]
When using the `posts/<post_id>.json` endpoint, if a deleted post with children is input, it will sometimes return the appropriate children of that post.

An example post which functions correctly: 1219272

An example post which does not function correctly: 6268

Searching for `parent:6268` will return a post which has 6268 as its parent; Yet while using the api 6268 says it has no children.

The issue seems to only be present on posts that were deleted before the migration. 6268 was deleted a long time ago while 1219272 was deleted 10 hours ago.

**Comment by kiranoot** [comment]
Old posts were not correctly marked in the database if they had children. I created a script to go through and fill in old posts so that they have the correct child status flags set. This problem should slowly resolve over the next few hours.
