### ISSUE TITLE
XML-endpoints return a 403

### ISSUE THREAD

**Issue by Niko-O** [e621ng/e621ng#207]
The API XML-endpoints always returns a 403 for me and a few others. Example:
https://e621.net/posts/77119.xml
However, the JSON-variants work:
https://e621.net/posts/77119.json
This happens with all XML-endpoints I have tested.
If this is intentional, the "[...] it's likely that the script was what resulted in your request being blocked."-message is a bit confusing. Will the XML-endpoints be enabled again or will I have to migrate to JSON?

**Comment by kiranoot** [comment]
All XML APIs are gone and will not return.
