### ISSUE TITLE
Include users own vote score in post json from api

### ISSUE THREAD

**Issue by wlfio** [e621ng/e621ng#210]
Adding the 1/0/-1 score a user has given to a post puts almost all data a user could want about a post into one request leading to fewer api hits.

Ruby isnt my forte so this is just a guess at the implementation. Appologies if it is of no help

```ruby
# in the serializer

  def score
    {
        up: object.up_score,
        down: object.down_score,
        total: object.score,
        own: object.own_vote_score # add this?
    }
  end

# in the post model VoteMethods section

    def own_vote_score(user = CurrentUser.user) # method to return numeric 1 > -1 score
      vote = self.own_vote(user)
      voted = !vote.nil?
      vote_score = voted ? vote.score : 0
      vote_score
    end
```

**Comment by kiranoot** [comment]
As noted in other issues about this topic, this causes a database query per post, which isn't acceptable in a bulk retrieval endpoint. I will be looking at other ways to possible present this information, but it is unlikely short term.
