### ISSUE TITLE
iqdb_queries returns 500 on non-whitelisted URL

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#213]
**Bug overview description.**
Using a URL that is not whitelisted with the `/iqdb_queries` page errors with a 500 response code and the text `An unexpected error occurred.`.

**What is the expected behavior?**
Expected behavior is for the site to inform me that it will not perform a search on a URL that is not whitelisted.

**What actual behavior is given instead?**
A 500 response with `An unexpected error occurred.` is returned instead

**Can you reproduce the bug every time?**
Yes. Reddit URLs are not whitelisted and will provide an error every time. [Here](https://i.redd.it/yvamwh02fpn41.png) is a URL that will produce an error.

**What steps did you take to replicate this bug?**
Attempted with a few different links. Some of which were whitelisted, others were no.

**Errors or other messages returned (if any).**
```
An unexpected error occurred.

Log ID: e7ef6c3a-d72d-4a1d-98bd-a2d7fa8c47cf
```

**Comment by Earlopain** [comment]
Not 100% sure on the commit but this problem does not occur anymore.
