### ISSUE TITLE
Missing created_at column in favorites table

### ISSUE THREAD

**Issue by noirscape** [e621ng/e621ng#224]
Error message (as produced by a fresh deploy):

```
ActionView::Template::Error exception raised

PG::UndefinedColumn: ERROR: column "created_at" does not exist LINE 1: ...orites" WHERE "favorites"."user_id" = $1 ORDER BY "created_a... ^ 


    app/presenters/user_presenter.rb:61:in `map'
    app/presenters/user_presenter.rb:61:in `favorites'
    app/views/users/_post_summary.html.erb:12
    app/views/users/show.html.erb:13
    app/controllers/users_controller.rb:57:in `show'
```
This occurs when trying to visit the profile page after favoriting a post as any user.

Referencing the schema, Favorite model (and the actual database), this column does indeed not exist in the database. It would seem this column would have to be added for favorites to work?

**Comment by Earlopain** [comment]
Fixed in https://github.com/zwagoth/e621ng/commit/804903c67d6324368475022cc47d2ce9d81c72df
