### ISSUE TITLE
Some SWF posts have negative sizes

### ISSUE THREAD

**Issue by Niko-O** [e621ng/e621ng#225]
A search for `width:<0 status:any` finds a hand full of posts with negative sizes. For example post 7709 is -888 by -613 in size. All of them are SWF files. Post 366902 is the only one being not deleted, but it does not show properly in my browser. (I have to click "Download" to view it, then it works fine.)

**Comment by Sasquire** [comment]
This is a known bug. Last I checked there were not plans to fix any of them. The error with `width` and `height` only seems to effect swf files. Some posts have a negative `score_down`. Post 2257113 is an example of the latter.
