### ISSUE TITLE
Old deleted posts have file extensions "del.png" and "del.jpg"

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#227]
Post 185858 has an unexpected file extension of "del.png" and posts 185854 and 185853 have "del.jpg" as their file extension. Switching these to just be "png" and "jpg" would make these posts be in line with the current file types.

Maybe there should be an issue cataloging all of the incorrect metadata that is on the site.

**Comment by Niko-O** [comment]
I found the following posts where the extension matches "%.%":
182904	"del.swf"
185787	"del.jpg"
185853	"del.jpg"
185854	"del.jpg"
185858	"del.png"
185928	"del.jpg"
185940	"del.png"
They are all deleted posts.

**Comment by Earlopain** [comment]
Certainly took a while, but I manually fixed these posts. These files seem to be missing from the server, but at least the metadata is now correct
