### ISSUE TITLE
Getting failbooru when installing

### ISSUE THREAD

**Issue by van-sprundel** [e621ng/e621ng#231]
Currently going through the installation, I've done every step but it seems to just give me code 500  `"Failbooru Something went wrong."` every time. I don't really know how to debug this, since I can't get any logs, and the VBox logs aren't that helpful.
I'm installing on a Windows computer.

I did find that this shell file doesn't get run, so I manually installed ruby on vagrant. No success.
![image](https://user-images.githubusercontent.com/55579979/90980509-1b89f780-e55c-11ea-8e7b-4f74f938cb86.png)

**Comment by highcup** [comment]
The 500 error you get when you first install e621ng is because the hostname "e621.lc"  was not added as a configured host in development.rb. Pull request #232 should fix your problem.

**Comment by van-sprundel** [comment]
Manually added the commit, but no success. I think the problem is that ruby-setup.sh doesn't get executed, and it has the command in it that runs the setup at the end. Could it be that the system is mounted with the noexec option? like [`here?`](https://unix.stackexchange.com/questions/203371/run-script-sh-vs-bash-script-sh-permission-denied)

**Comment by highcup** [comment]
Just to clarify you are getting this error when using the vagrant script to setup the e621 vm on windows right?

**Comment by van-sprundel** [comment]
Yes, after `vagrant up` is done, it shows permission denied for ruby-setup.sh. I assume thats the reason the setup fails.

**Comment by Earlopain** [comment]
The project uses docker now which should improve the setup progress tremendously.
