### ISSUE TITLE
Sorting tag aliases by date results in unstable, nulls-first sorting

### ISSUE THREAD

**Issue by ElAcechador** [e621ng/e621ng#242]
Any tag alias or implication request older than febuary 2012 (likely when the feature was added to the old e6 system) will register as having a null date of creation. For some reason, the "Creation date" ordering is date descending with nulls first (even though the nulls are older), but more importantly the sorting order for null elements is non-deterministic and will change when refreshing and changing pages.

I don't mind the sorting not respecting the actual creation date when that date was never recorded in the first place (though I suppose it could always fallback to IDs or something), but the order should at least be persistant while going through each page.

**Comment by kiranoot** [comment]
Fixed in e8e3a84d3fe3405af750ae88f24f16fd650
