### ISSUE TITLE
Autocomplete middle click action always opens a tag search

### ISSUE THREAD

**Issue by Earlopain** [e621ng/e621ng#251]
There are a few pages which feature autocomplete, most importantly when you are searching for a post.

But Wikis, Pools, Artists and probably a few more also feature autocomplete. Currently these don't to what I expect them to do on middle clicking:

- Wikis: Opens a tag search for the page I wanted to look at
- Pools: Opens a tag search for the pool name, which will probably result in no posts being found
- Artists: Opens a tag search for the artist

It seems like they all just treat the returned text as a tag. If I am already on the dedicated page for those I expect to also be redirected to them on search. Heres an example for wiki autocomplete:

![image](https://user-images.githubusercontent.com/14981592/113039467-fb788180-9197-11eb-976e-af30f94cbd4c.png)

Is it ok if I open a PR which changes this behaviour?

**Comment by kiranoot** [comment]
Yeah, this seems like a positive change.
