### ISSUE TITLE
Tag autocomplete returns root element instead of empty array only when no matches

### ISSUE THREAD

**Issue by Earlopain** [e621ng/e621ng#253]
Compare https://e621.net/tags/autocomplete.json?search[name_matches]=iomngwmgwegw with https://e621.net/tags/autocomplete.json?search[name_matches]=anthro

This results in a js error when trying to map it in `autocomplete.js.erb` because mapping an array vs mapping an object obviously behaves differently. Other autocomplete sources work fine because they use the model endpoint directly. Tags are special in that they don't use the normal search methods like the rest.

https://github.com/zwagoth/e621ng/blob/1c61801bebefaf86d1065586393b8a793cb60e2e/app/models/tag.rb#L1142-L1159

I tried looking into it but don't understand why it suddenly adds the root element, so I'll just leave this as an issue for now

**Comment by kiranoot** [comment]
This is related to how rails formats the json content type and collections. It tries to interrogate the model name to format collections with by picking the first element and checking if it a model, and if it can't determine what type it is, it gives up and formats using a different style.

I don't recall if there is a good fix for this or not, I recall it being part of the controller setup and not part of the model.

**Comment by kiranoot** [comment]
Fixed in a9f0033ef48b08ce60132988d808b2e95281f44b
