### ISSUE TITLE
Post page claims it has 0 children

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#258]
Let's say there exists post A and post B. The following actions are performed:
1. Set post A as parent of post B.
2. Flag post A as inferior to post B.

Expected behavior: post B becomes the parent of post A.
Actual behavior: post A remains the parent of B, but post B gets a "0 children" notice as well.

[Example](https://user-images.githubusercontent.com/1503448/139155235-714014fc-0428-48da-99d3-83d5518f79a7.png)

Presumably, this happens because post B has the `has_active_children` property set to `true`, but does not actually become the parent of post A.

**Comment by kiranoot** [comment]
Is this only true for posts that would become parents of one another? I feel like this is the parent loop check kicking in and preventing the change from completing, but the flag still getting set, but want to make sure I have the scope correct.

**Comment by bitWolfy** [comment]
Yes, seems to be an issue specifically with the posts becoming parents of each other.
This isn't an issue with just setting the parent manually, though. If post A is parent of B, and you set B as parent of A, then the original relationship gets removed.
