### ISSUE TITLE
Error 422 when trying to approve a post that someone else has already approved

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#260]
This is a minor complaint, but still slightly annoying.

Before approving a post, I do several things - check the sources, try to find a better version, and so on. While doing that, it is not impossible that another janitor also opens that post and approves it. In fact, it happens a couple of times every day.

When clicking on the "Approve" button of such post, I would expect the page to just reload like it normally does after the approval goes through. It does not - the "Posts updated" notification just sits there for a little while before going away.
I believe this happens because a request sent to `https://e621.net/moderator/post/approval.json` returns error 422, and the script does not know how to deal with that.

**Comment by kiranoot** [comment]
This is part of a larger problem involving the queued post update system. The system doesn't understand how to handle and display errors, and so it always returns a "Post updated" message. There are a few different problems. One is that if there are a large number of queued actions, stopping in the middle makes it hard to tell where the progress stopped. If the progress continues it becomes hard to tell which individual items failed.

The current situation of having no feedback is also extremely poor. I will revisit the old site source code and see what was being done there, as this problem had been looked into and partially addressed, and the newer danbooru source code didn't have any provisions for that type of error handling.

**Comment by Earlopain** [comment]
Fixed by simply always reloading, even if the request failed. This doesn't address the root problem, but should be an improvement nevertheless.
