### ISSUE TITLE
Deleted posts do not get displayed if the status: meta-tag contains uppercase letters

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#262]
Specifically, deleted posts do not get displayed if there are any uppercase letters in the second half of the meta-tag.
For example, searching for [order:id_asc+status:any](https://e621.net/posts?tags=order:id_asc+status:any) shows all posts, but searching for [order:id_asc+status:Any](https://e621.net/posts?tags=order:id_asc+status:Any) does not display any deleted posts.

This is most evident if searching for [status:deleted](https://e621.net/posts?tags=status:Deleted).

**Comment by kiranoot** [comment]
Fixed in 9b5e0e9bb8422737bc9bf
