### ISSUE TITLE
On the post changes page, using the "Apply Tag Script To Selected" adds "undefined" tag instead.

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#269]
Steps:
1. Go to https://e621.net/post_versions?search[post_id]=12345
2. Select the checkbox next to the last change in the list
3. Click "Apply Tag Script To Selected"
4. Reload page

Expected result: the tag script should be applied to the post
Actual result: `undefined` is added to the tag list

Originally reported by TheVileOne on Discord.

**Comment by kiranoot** [comment]
Oh Javascript. How I love thee.

**Comment by kiranoot** [comment]
Fixed in 414d6b3e0134a704893d48064cd005
