### ISSUE TITLE
favorites on e9 arent paging correctly

### ISSUE THREAD

**Issue by clragon** [e621ng/e621ng#283]
When visiting the favorites page on e9, the pages will show very little posts.
it seems to use the same requests as e6 and then just filter posts with rating:s. 

I feel like the page should be filled up with posts, just like other post pages. 

this is also very detremential to API requests, as normally, requesting new pages should be stopped when an empty list is returned.
The current behaviour however can return empty pages between pages that contain posts, making the pagination cut off early.

**Comment by kiranoot** [comment]
This page isn't really designed to be used on e9 with lots of non-safe posts. The way the request works internally depends on a non-standard sorting order, so filtering out non-safe posts is extremely slow and non-deterministic in speed. Doing a join to load post ratings is also too slow to maintain.

If you want favorited posts but don't care about the sorting order, run a post search for `fav:name` and use the results from that, as it will properly fill pages for you.
