### ISSUE TITLE
Banned users can no longer access their accounts

### ISSUE THREAD

**Issue by Weblure** [e621ng/e621ng#292]
Prior to the migration, blocked users could still log into their accounts to access their favorites, a cross-browser blacklist, and other basic features. The purpose of a block was to prevent an undesirable users from interacting with the rest of the community. Completely locking a user out of their account serves no added purpose and encourages ban evasion, especially now that a global blacklist is forced onto anonymous users.

Ideally, the best solution would be to once again allow blocked users to access their account, while restricting them from commenting, voting, and using other community features. Unfortunately, this would likely involve a large amount of work.

As a temporary alternative, anonymous users could be given the option to disable the global blacklist, after consenting to an agreement. Oddly, the global blacklist seems to be handled on the server side, so I'm not even sure where to begin looking. If anyone can point me in the right direction, it'd be appreciated.

**Comment by Weblure** [comment]
On second thought, the functionality is already there -- for unverified accounts. That same functionality could be probably be extended to banned accounts as well.

**Comment by kiranoot** [comment]
This was an intentional change that went through several admins. Once banned, users rights to an account is revoked. Edge cases and interactions with banned accounts has been a headache for ages. Ban evasion is against the rules.

**Comment by Weblure** [comment]
> This was an intentional change that went through several admins. Once banned, users rights to an account is revoked. Ban evasion is against the rules.

Banned users are restricted from much of the site's content and functionality. Permanently banned users are incentivized to evade their ban, simply so they can use the website properly. Saying that "ban evasion is against the rules" is like telling someone on death row that trying to escape is illegal. It's not productive in any sense.

A permanently banned user is less like to create a new account if it was not required in order to use basic non-community features. Since they have to create a new account anyway, they're more likely to use the community features they were barred from, since there's really no reason for them not to by that point.

> Edge cases and interactions with banned accounts has been a headache for ages.

That sounds more like a design problem from the old website. Like I mentioned, you already have a similar system in place for unverified accounts. If it works for those, why wouldn't it also work for banned users?

There's also the more pressing concern of how this is used to retroactively justify bans. A user receives a poorly-reasoned ban, submits an appeal, and then they don't receive a response for an unreasonable length of time. They're barred from basic website functionality and other content, effectively giving them little choice beyond making a new account while waiting months for a response. Then when they do, their appeal is denied on grounds of them having made a new account, regardless of them not using it for any nefarious purposes.

**Comment by DraconicNEO** [comment]
> This was an intentional change that went through several admins. Once banned, users rights to an account is revoked. Edge cases and interactions with banned accounts has been a headache for ages. Ban evasion is against the rules.

I agree with what @Weblure said This implementation is more likely to cause issues down the road and is incredibly stupid considering you've already given out the worst punishment you can to them, when you ban people you're saying they can't use the community options because they were causing trouble but now you're saying they don't have the right to use the site at all when they could do it before. Saying "Ban evasion is against the rules." is really stupid at this point considering there's nothing (legal) you can really do to enforce it anymore. Since they no longer can use the site properly it's inevitable they're going to do it and if they already know that you're watching and collecting information on them 1984 style it'll be increasingly difficult if not flat out impossible to enforce it, especially with coordinated/targeted efforts.

**Comment by Weblure** [comment]
> > This was an intentional change that went through several admins. Once banned, users rights to an account is revoked. Edge cases and interactions with banned accounts has been a headache for ages. Ban evasion is against the rules.
> 
> I agree with what @Weblure said This implementation is more likely to cause issues down the road and is incredibly stupid considering you've already given out the worst punishment you can to them, when you ban people you're saying they can't use the community options because they were causing trouble but now you're saying they don't have the right to use the site at all when they could do it before. Saying "Ban evasion is against the rules." is really stupid at this point considering there's nothing (legal) you can really do to enforce it anymore. Since they no longer can use the site properly it's inevitable they're going to do it and if they already know that you're watching and collecting information on them 1984 style it'll be increasingly difficult if not flat out impossible to enforce it, especially with coordinated/targeted efforts.

The entire thing just feels like a joke at this point. After waiting four years to get a genuine appeal since eating a zero-warning permaban over a [single rude comment](https://e621.net/posts/1553759#comment-3887841), I've entirely given up on the administration team. They've since blocked my IP after I resorted to making alt accounts just so I could properly use the website, go figure.

**Comment by DraconicNEO** [comment]
> > > This was an intentional change that went through several admins. Once banned, users rights to an account is revoked. Edge cases and interactions with banned accounts has been a headache for ages. Ban evasion is against the rules.
> > 
> > 
> > I agree with what @Weblure said This implementation is more likely to cause issues down the road and is incredibly stupid considering you've already given out the worst punishment you can to them, when you ban people you're saying they can't use the community options because they were causing trouble but now you're saying they don't have the right to use the site at all when they could do it before. Saying "Ban evasion is against the rules." is really stupid at this point considering there's nothing (legal) you can really do to enforce it anymore. Since they no longer can use the site properly it's inevitable they're going to do it and if they already know that you're watching and collecting information on them 1984 style it'll be increasingly difficult if not flat out impossible to enforce it, especially with coordinated/targeted efforts.
> 
> The entire thing just feels like a joke at this point. After waiting four years to get a genuine appeal since eating a zero-warning permaban over a [single rude comment](https://e621.net/posts/1553759#comment-3887841), I've entirely given up on the administration team. They've since blocked my IP after I resorted to making alt accounts just so I could properly use the website, go figure.

I recommend calling up your ISP to have your IP address changed, but before that remove all site data from your browser as well as history (if you use Firefox put the site in a dedicated container, this reduces the amount of data they can collect from your browser).

There are other tools that you can use to circumvent IP bans as well but I won't share them here since that would benefit the horrible people who run this site. If you like though I could tell you about them privately.
