### ISSUE TITLE
Upload form uses the wrong wiki link format

### ISSUE THREAD

**Issue by bitWolfy** [e621ng/e621ng#301]
Steps to reproduce:
1. Open the [upload page](https://e621.net/uploads/new)
2. Add the following to the "Other tags" field: `anthro`
3. Click "Preview Final Tags" under the textarea
4. Click on "anthro" in the resulting list

Expected result: the following page will be opened in a new tab: https://e621.net/wiki_pages/show_or_new?title=anthro
Actual result: this page is opened instead: https://e621.net/wiki_pages/show_or_new?name=anthro

The URL uses the `name` parameter instead of `title`, which results in a broken page.
The "Related tags" are also similarly affected.

I believe that this comes from pull request #290.
Should be a relatively simple fix, I believe. @Earlopain

**Comment by Earlopain** [comment]
Yup, thats my fault. I already corrected it with https://github.com/zwagoth/e621ng/pull/297/commits/e5429de3660882cb96cbbdf73cd25a6c92f9c439 in pr #297 but only for previews. I'll correct the other one later today after I get back from work.

**Comment by Earlopain** [comment]
I fixed the issue for both cases, see the linked commit from #297

**Comment by bitWolfy** [comment]
Thank you! 👍
