### ISSUE TITLE
Problem with Vagrant Service

### ISSUE THREAD

**Issue by Firestar311** [e621ng/e621ng#311]
I believe that this is slightly different than #231 As I found an error in the service log
I run Ubuntu Servers and I was able to get into SSH and found this error: https://gyazo.com/dd8e07134a422bc03576e113c0249d65
This is after running the vagrant setup script, restarting my computer and trying again.

**Comment by liamwhite** [comment]
git has converted the files in your repository to Windows line-endings; you must disable this behavior and recreate your working directory to fix it.
1. `git config --global core.autocrlf false`
2.  `rm -rf *`
3.  `git checkout -- .`

**Comment by Earlopain** [comment]
@Thomas0398 did this fix the issue for you?

**Comment by bitWolfy** [comment]
I had the same issue, and the fix did work.

**Comment by Earlopain** [comment]
Added the necessary fix to the readme troubleshooting steps. https://github.com/zwagoth/e621ng/commit/22a4fe038dabd65df74550e2b63a2c43c2e2a596
