### ISSUE TITLE
Add scale to window resolution support.

### ISSUE THREAD

**Issue by kiranoot** [e621ng/e621ng#80]
E6 has a scaling mode where the image is constrained to the horizontal width of the page. This needs to be implemented again on the new site. The support code is already there because it's capable of scaling note contents to the sample images. Likely just needs an async JS event handler and some CSS rules.

**Comment by liamwhite** [comment]
max-width: 100vw

**Comment by kiranoot** [comment]
That works for the CSS, yes, but there still needs to be something that properly scales the notes overlay.
