### ISSUE TITLE
API Endpoint to view pools a post is in

### ISSUE THREAD

**Issue by Sasquire** [e621ng/e621ng#90]
There is no easy way to find what pools a given post belongs to. The options available are to iterate through all pools until the desired post is found, or the HTML page of the post could be scraped.

Ways this could be solved
* Change `/pools.json` to accept parameter `post_id`
* Add `/pools/post.json` with paremeter `id`
* Have `/post/show.json` and/or `/post/index.json` include a `pools` field that is an array

**Comment by kiranoot** [comment]
Fixed in bf4f9d77a9ae56c
