### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by kdoshere** [e621ng/e621ng#96]
Hi

Image fit:
It should be adjusted to fit as the default choice when the resolution is below 660. Both for registered and anonymous user because the current view from a mobile device without logging in makes you have to click to get the adjustment and as a user it forces the fit option as default.

Email blacklist:
The issue is when you change an email, it seems like when you do that it won't do the validation to see if that email is in the blacklist or not.

Forum categories:
The problem is that when deleting a category you'll get: undefined method `id'....

Help:
It seems to crash when including a related entry. Also from the show view, the edit wiki option seems like its pointing to the wrong place (For example when trying to edit the wiki entry with id 23 related to the help entry 2, it would instead try to edit the wiki entry with id 2 when it should point to the entry with id 23).

**Comment by kiranoot** [comment]
Thank you for the feedback. I'll make the required bug fixes in a day or two when I find time.

**Comment by kiranoot** [comment]
I believe I will just add a forced fit to window css option for the sample sized images. The intention of samples is not to make them fit to the window better, but actually to make them load more quickly and trade off bandwidth usage for visual clarity. So letting them spill over the edges of the window is not an ideal situation. If people want a full sized image they can swap the view mode to have one.

**Comment by kdoshere** [comment]
Indeed, it makes more sense and seems a better option.
